LLS Notes on /asl/prod/matlab

* Overall
  1. To run interactively without clustcmd just set JOBS and then
     execute the relevant script.  Something like:
 : >> JOB = datenum(2011,2,10)
 : >> rtp_core
   Another way to accomplish the same feat is to start matlab up with
   the desired day in the JOB environment variable:
 : taro$ JOB=20110310 matlab -nodesktop
 : >> rtpcore

* CrIS
** Problems
*** rtp/rtp_core.m
  - Do not want to switch from sdr4 to sdr60 files automatically.
  - Profile attributes are incorrect (pattr).  Reason is in iudef, not
    udef.  (FIXED.)
  - Need to get exact altitude, is it in metadata?  824km?  Fix in
    mkconv4.m as well?
  - iok not used now, remove unneeded code?
** Cleanups
  - rtp_cris_subset runs proxy_box_to_ham for small number of channels
    needed in finding clear.  This can be done more efficiently.  It
    is being done for all channels now using old code.  Is only needed
    for a handful of channels.
** Immediate Changes Needed
  1. Update =cris/readers/readsdr_rtp= with updated reader that pulls
     in many more flags, etc.
  2. The rtp outputs contain something in prof.udef(1,:) that I cannot
     find in the code anywhere.  What is this, who and why is it set?
     The values go from 0:1.
** Questions
  - Set output directory tree using variable =prod_dir=.  Set this in
    =cris/rtp/cris_paths.m=. Generally set to
    ='/asl/data/rtprod_cris'= but to ='/asl/data/rtprod_cris_test'=
    for testing.  This seems reasonable, you just need to change this
    when deploying a new version in the production tree if not set
    properly.
  - What does structmerge do?  Line 93 of =rtp/rtp_core.m=  
** Observations
*** udefs
The defined udefs right now are:
  1. iudef(1,:) = Reason
  2. udef(10:12,:) = Spacecraft x,y,z positions
  3. udef(13,:) = \Delta B(T) from xuniform.m

* AIRS
** Observations
 1. AIRS rtp need =mkmetadata.m= to be run, which gets the AIRS flags
    we need (that are not in AIRXBCAL).  It uses opendap, and can use
    pre-downloaded data if done.  That data is put in
    =/asl/data/airs/META_DATA= on taro.  I think =mkmetadata.m= can
    be run stand-alone, so Paul or I can run it before a disk is made
    for me during CrIS Cal/Val if the rtp files have not yet been
    made.
** Cleanups
  1. There are two very similar and complicated Mfiles in =airs/utils=
     named =data_to_calnum_l1b.m= and =data_to_calnum_l1bcm.m=.  This
     is very dangerous, using such similar names and similar code.
     The \*libcm version contains rtime and granule as inputs, while
     \*l1b version does not.  This needs to be cleaned up.
  2. =airs/rtp/sarta_core.m= picks the SARTA versino based on date.
     Make sure that is what I want.  I think the SARTA versions should
     be in a separate input, not in the source code.

* RTP
  1.  Switch to the new rtpread function.  Paul says that worked for
      him. 
  





