#!/bin/sh
#
# Run gstats for a given date range and save it to a predeclared folder.  
#  For usage and detailed information run this script without any arguments.
#
#

POST='trans_obs_ecm_ctrall'
prod='airs'


# catch a user kill signal and clean up any temporary / old files sitting around
on_die()
{
  echo "Dying..."
  /bin/rm -f $lock
  exit
}
trap 'on_die' 2 3 5 15


# choose and create output directory
dir=/asl/data/rtprod_$prod/gstats/gsx_daily_$POST
mkdir -p $dir 2> /dev/null

# the output file name 
out=$dir/${prod}_daily_${1:0:8}.mat

# create / test to see if this is already being processed by creating a temporary lock file
lock=$dir/.${prod}_${1:0:8}.lock
echo lockfile=$lock
lockfile -0 -r0 -l3600 $lock || exit

# Loop over the given date range and create a file mask of all the rtp files
arr=(`echo $1 | sed "s/:/ /g"`)  # split the input argument into two sets of numbers
for date in `/asl/opt/bin/datelist ${arr[0]}:${arr[2]}`; do
    year=${date:0:4}; mo=${date:4:2}; day=${date:6:2}
    filemask="$filemask '/asl/data/rtprod_$prod/$year/$mo/$day/AIRS_L1B_CTR_*'";
done
echo filemask=$filemask


# Start up matlab with this setup:

defaults="addpath /asl/matlab/rtptoolsV201/;\
gtops = struct; \
gtops.clrflag = 1:2; \
gtops.transcom_bins=0:23; \
gtops.secang_bins=[1 1.028 1.1 1.31 1.72]; \
gtops.solzen_bins=[0 90 180]; \
gtops.skip_calc = 1; \
gtops.klayers = ''; \
gtops.calflag_bit=nan; \
gtops.inc_fields={'ptemp','dbt','robs1','rtime_avg','secang_avg','stemp','gas_1','gas_2_avg','gas_3','gas_4_avg','gas_5_avg','gas_6_avg','gtotal_avg','spres','salti_avg','cfrac_avg','wspeed_avg','palts_avg','plevs','solzen','secang','rlat_avg','rlon_avg'}; \
gtops.filemask={$filemask}; \
"


# Execute matlab
matlab -nodisplay -nodesktop -nojvm -nosplash -r "$defaults;  \
  airs_paths;gstats(gtops,'${out}'); exit;" 

# Clear the lock file to allow the process to be re-ran
/bin/rm -f $lock &> /dev/null
