function Etc_show_error(errstr)
% function Etc_show_error(errstr)
%
% Display the error structure errstr which was generated by the MATLAB command lasterror.
%

fprintf('\nError: %s (%s)\n\n',errstr.message, errstr.identifier);

for i=1:length(errstr.stack)
%  fprintf('file:  %s\n',errstr.stack(i).file);
%  fprintf('name:  %s\n',errstr.stack(i).name);
%  fprintf('line:  %d\n',errstr.stack(i).line);
  fprintf('In ==> %s>%s at %d\n\n',errstr.stack(i).file, errstr.stack(i).name, errstr.stack(i).line);
end

end
